import React, { useState } from 'react';
import { catchesAPI } from '../services/api';

export default function LogCatchPage() {
  const [formData, setFormData] = useState({
      species: '',
          weight: '',
              length: '',
                  location: '',
                    });
                      const [photo, setPhoto] = useState(null);
                        const [loading, setLoading] = useState(false);
                          const [message, setMessage] = useState({ type: '', text: '' });

                            const handleInputChange = (e) => {
                                const { name, value } = e.target;
                                    setFormData(prev => ({ ...prev, [name]: value }));
                                      };

                                        const handlePhotoChange = (e) => {
                                            setPhoto(e.target.files[0]);
                                              };

                                                const handleSubmit = async (e) => {
                                                    e.preventDefault();
                                                        setLoading(true);
                                                            setMessage({ type: '', text: '' });

                                                                try {
                                                                      // Create the catch record
                                                                            const catchRecord = await catchesAPI.create(formData);
                                                                                  
                                                                                        // Upload photo if provided
                                                                                              if (photo) {
                                                                                                      await catchesAPI.uploadPhoto(catchRecord.id, photo);
                                                                                                            }

                                                                                                                  setMessage({ type: 'success', text: 'Catch logged successfully!' });
                                                                                                                        setFormData({ species: '', weight: '', length: '', location: '' });
                                                                                                                              setPhoto(null);
                                                                                                                                    
                                                                                                                                          // Clear success message after 3 seconds
                                                                                                                                                setTimeout(() => setMessage({ type: '', text: '' }), 3000);
                                                                                                                                                    } catch (error) {
                                                                                                                                                          setMessage({ type: 'error', text: error.message || 'Failed to log catch' });
                                                                                                                                                              } finally {
                                                                                                                                                                    setLoading(false);
                                                                                                                                                                        }
                                                                                                                                                                          };

                                                                                                                                                                            return (
                                                                                                                                                                                <div className="max-w-2xl mx-auto p-6">
                                                                                                                                                                                      <h2 className="text-3xl font-bold mb-6">Log Your Catch</h2>
                                                                                                                                                                                            
                                                                                                                                                                                                  {message.text && (
                                                                                                                                                                                                          <div className={`mb-4 p-4 rounded ${message.type === 'success' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                                                                                                                                                                                                                    {message.text}
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                        <form onSubmit={handleSubmit} className="bg-white p-8 rounded-lg shadow">
                                                                                                                                                                                                                                                <div className="mb-6">
                                                                                                                                                                                                                                                          <label className="block text-sm font-medium text-gray-700 mb-2">
                                                                                                                                                                                                                                                                      Species
                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                                                  name="species"
                                                                                                                                                                                                                                                                                                                              value={formData.species}
                                                                                                                                                                                                                                                                                                                                          onChange={handleInputChange}
                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                                  placeholder="e.g., Bass, Trout, Catfish"
                                                                                                                                                                                                                                                                                                                                                                              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-2 gap-4 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm font-medium text-gray-700 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                            Weight (lbs)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name="weight"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={formData.weight}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={handleInputChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        step="0.1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="0.0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Length (inches)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="length"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={formData.length}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={handleInputChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          step="0.1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="0.0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label className="block text-sm font-medium text-gray-700 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Location
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name="location"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={formData.location}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleInputChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="e.g., Lake Michigan, Local Pond"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm font-medium text-gray-700 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Photo (optional)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handlePhotoChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full px-4 py-2 border border-gray-300 rounded-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {photo && <p className="text-sm text-gray-600 mt-2">Selected: {photo.name}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full bg-blue-600 text-white py-3 rounded-lg font-semibold hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? 'Logging Catch...' : 'Log Catch'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }